In [30]:
import numpy as np
import math
np.set_printoptions(suppress=True)
A = np.random.rand(2,2)
f = np.random.rand(2,1)
# A= np.array([[10,-7,0],[-3,2.099,6],[5,-1,5]])
# f = np.array([[7],[3.901],[6]])
print("Original Random 2x2 Coefficient Matrix A:\n",A)
print("Original Random Vector Matrix B:\n",f)

# # Original Random 2x2 Coefficient Matrix A:
# A = np.array([[0.39245808 ,0.42972412], [0.26497132, 0.50848123]])
# f = np.array([[0.0841236 ],[0.78500416]])

Original Random 2x2 Coefficient Matrix A:
 [[0.52992941 0.91692432]
 [0.42627025 0.31118235]]
Original Random Vector Matrix B:
 [[0.23974492]
 [0.48604119]]


In [31]:
def convertToSig(a_number,significant_digits):
    if(type(a_number) == np.ndarray):
        for idx,i in  np.ndenumerate(a_number):
            if(a_number[idx]!=0):
                a_number[idx] = round(a_number[idx], significant_digits - int(math.floor(math.log10(abs(a_number[idx])))) - 1)
        return(a_number)    
    elif(a_number != 0.):
        rounded_number =  round(a_number, significant_digits - int(math.floor(math.log10(abs(a_number)))) - 1)
        return(rounded_number)
    else:
        return(a_number)

In [32]:
def GaussElimWithPivot(A, f,digits):
    A=np.around(A,digits)
    f=np.around(f,digits)
    print("Executing 2x2 system of equations with Pivot for ",digits," significant digits!!\n\n")

    print("Random 2x2 Coefficient Matrix A of ",digits," significant digits:\n",A)
    print("Random Vector Matrix B of ",digits," significant digits:\n",f)
   
    print("Equations which must be solved based on above matrix:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), f[i]))
 #Caluculating the LU using Pivoting
    n = len(f)
    for i in range(0,n-1):     # Step - Looping through the columns of the matrix
        if np.abs(A[i,i])==0:
            for k in range(i+1,n):
                if np.abs(A[k,i])>np.abs(A[i,i]):
                    A[[i,k]]=A[[k,i]]             # Step Swapping ith and kth rows to each other
                    f[[i,k]]=f[[k,i]]
                    break
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            m = convertToSig(A[j,i]/A[i,i],digits)
            A[j,:] = convertToSig(A[j,:] - convertToSig(m*A[i,:],digits),digits)
            f[j] = convertToSig(f[j] - convertToSig(m*f[i],digits),digits)        
 #Caluculating the final output
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = convertToSig(f[n-1]/A[n-1,n-1],digits)    # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ = convertToSig(sum_ + A[i,j]*x[j],digits)
        sum_ = convertToSig(sum_,digits)
        x[i] = convertToSig((f[i] - sum_)/A[i,i],digits)
    print("Solution is as below:")
    return x

In [33]:
def GaussElimWithoutPivot(A, f,digits):
    print("Executing 2x2 system of equations without Pivot for ",digits," significant digits!!\n")
    A = np.around(A,digits)
    f = np.around(f,digits)
    print("Random 2x2 Coefficient Matrix A of ",digits," significant digits:\n",A)
    print("Random Vector Matrix B of ",digits," significant digits:\n",f)
    
    print("Equations which must be solved based on above matrix:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) 
        for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), f[i]))
    #LU Decomposition with no pivoting
    n = len(f)
    for i in range(0,n-1):     # Loop through the columns of the matrix
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            if A[i,i] == 0:
                print("Error: Zero on diagonal!")
                print("Need algorithm with pivoting")
                break
            m = convertToSig(A[j,i]/A[i,i],digits)
            A[j,:] = convertToSig(A[j,:] - convertToSig(m*A[i,:],digits),digits)
            f[j] = convertToSig(f[j] - convertToSig(m*f[i],digits),digits)
    #Using Back Substitution
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = convertToSig(f[n-1]/A[n-1,n-1],digits)   # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ =convertToSig(sum_ + convertToSig(A[i,j]*x[j],digits),digits)
        x[i] = convertToSig(((f[i] - sum_)/A[i,i]),digits)
    print("\nSolution is as below:")
    return x

In [34]:
print(GaussElimWithoutPivot(A, f,5))

Executing 2x2 system of equations without Pivot for  5  significant digits!!

Random 2x2 Coefficient Matrix A of  5  significant digits:
 [[0.52993 0.91692]
 [0.42627 0.31118]]
Random Vector Matrix B of  5  significant digits:
 [[0.23974]
 [0.48604]]
Equations which must be solved based on above matrix:
[0.52993*x1 + 0.91692*x2] = [[0.23974]]
[0.42627*x1 + 0.31118*x2] = [[0.48604]]

Solution is as below:
[ 1.6422  -0.68765]


In [35]:
print(GaussElimWithPivot(A, f,3))

Executing 2x2 system of equations with Pivot for  3  significant digits!!


Random 2x2 Coefficient Matrix A of  3  significant digits:
 [[0.53  0.917]
 [0.426 0.311]]
Random Vector Matrix B of  3  significant digits:
 [[0.24 ]
 [0.486]]
Equations which must be solved based on above matrix:
[0.53*x1 + 0.917*x2] = [[0.24]]
[0.426*x1 + 0.311*x2] = [[0.486]]
Solution is as below:
[ 1.64  -0.688]


In [36]:
print(GaussElimWithPivot(A, f,4))

Executing 2x2 system of equations with Pivot for  4  significant digits!!


Random 2x2 Coefficient Matrix A of  4  significant digits:
 [[0.5299 0.9169]
 [0.4263 0.3112]]
Random Vector Matrix B of  4  significant digits:
 [[0.2397]
 [0.486 ]]
Equations which must be solved based on above matrix:
[0.5299*x1 + 0.9169*x2] = [[0.2397]]
[0.4263*x1 + 0.3112*x2] = [[0.486]]
Solution is as below:
[ 1.642  -0.6876]


In [37]:
print(GaussElimWithPivot(A, f,5))

Executing 2x2 system of equations with Pivot for  5  significant digits!!


Random 2x2 Coefficient Matrix A of  5  significant digits:
 [[0.52993 0.91692]
 [0.42627 0.31118]]
Random Vector Matrix B of  5  significant digits:
 [[0.23974]
 [0.48604]]
Equations which must be solved based on above matrix:
[0.52993*x1 + 0.91692*x2] = [[0.23974]]
[0.42627*x1 + 0.31118*x2] = [[0.48604]]
Solution is as below:
[ 1.6422  -0.68765]


In [38]:
print(GaussElimWithPivot(A, f,6))

Executing 2x2 system of equations with Pivot for  6  significant digits!!


Random 2x2 Coefficient Matrix A of  6  significant digits:
 [[0.529929 0.916924]
 [0.42627  0.311182]]
Random Vector Matrix B of  6  significant digits:
 [[0.239745]
 [0.486041]]
Equations which must be solved based on above matrix:
[0.529929*x1 + 0.916924*x2] = [[0.239745]]
[0.42627*x1 + 0.311182*x2] = [[0.486041]]
Solution is as below:
[ 1.64219  -0.687626]


In [39]:
print(GaussElimWithoutPivot(A, f,3))

Executing 2x2 system of equations without Pivot for  3  significant digits!!

Random 2x2 Coefficient Matrix A of  3  significant digits:
 [[0.53  0.917]
 [0.426 0.311]]
Random Vector Matrix B of  3  significant digits:
 [[0.24 ]
 [0.486]]
Equations which must be solved based on above matrix:
[0.53*x1 + 0.917*x2] = [[0.24]]
[0.426*x1 + 0.311*x2] = [[0.486]]

Solution is as below:
[ 1.64  -0.688]


In [40]:
print(GaussElimWithoutPivot(A, f,4))

Executing 2x2 system of equations without Pivot for  4  significant digits!!

Random 2x2 Coefficient Matrix A of  4  significant digits:
 [[0.5299 0.9169]
 [0.4263 0.3112]]
Random Vector Matrix B of  4  significant digits:
 [[0.2397]
 [0.486 ]]
Equations which must be solved based on above matrix:
[0.5299*x1 + 0.9169*x2] = [[0.2397]]
[0.4263*x1 + 0.3112*x2] = [[0.486]]

Solution is as below:
[ 1.642  -0.6876]


In [41]:
print(GaussElimWithoutPivot(A, f,5))

Executing 2x2 system of equations without Pivot for  5  significant digits!!

Random 2x2 Coefficient Matrix A of  5  significant digits:
 [[0.52993 0.91692]
 [0.42627 0.31118]]
Random Vector Matrix B of  5  significant digits:
 [[0.23974]
 [0.48604]]
Equations which must be solved based on above matrix:
[0.52993*x1 + 0.91692*x2] = [[0.23974]]
[0.42627*x1 + 0.31118*x2] = [[0.48604]]

Solution is as below:
[ 1.6422  -0.68765]


In [42]:
print(GaussElimWithoutPivot(A, f,6))

Executing 2x2 system of equations without Pivot for  6  significant digits!!

Random 2x2 Coefficient Matrix A of  6  significant digits:
 [[0.529929 0.916924]
 [0.42627  0.311182]]
Random Vector Matrix B of  6  significant digits:
 [[0.239745]
 [0.486041]]
Equations which must be solved based on above matrix:
[0.529929*x1 + 0.916924*x2] = [[0.239745]]
[0.42627*x1 + 0.311182*x2] = [[0.486041]]

Solution is as below:
[ 1.64219  -0.687626]


In [43]:
import math
a_number=0.31387738
significant_digits=6
rounded_number =  round(a_number, significant_digits - int(math.floor(math.log10(abs(a_number)))) - 1)
print(rounded_number)

0.313877
