In [12]:
import numpy as np
def getRandomMatrix():
    return np.around(np.random.randn(3,3),4)
def getLUMatrices(A):
    n = A.shape[0]
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    for i in range(n):
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
    return L, U
def generate_diagonally_dominant_matrix():
    A = getRandomMatrix()
    D = np.diag(np.abs(A)) # Find diagonal coefficients
    S = np.sum(np.abs(A), axis=1) - D # Find row sum without diagonal
    L,U = getLUMatrices(A)
    C = -np.linalg.inv(np.identity(3)+L)*U
    if np.all(D > S) and np.linalg.norm(C,'fro') < 1:
        return A
    else:
        return generate_diagonally_dominant_matrix()
def testConvrgence(A):
    L,U = getLUMatrices(A)
    C = -np.linalg.inv(np.identity(3)+L)*U
    print("Test for convergence::",np.linalg.norm(C,'fro') < 1)
    
A = generate_diagonally_dominant_matrix()
b = np.random.rand(3,1)
print("Random Generated Co-efficient matrix is:\n",A)
print("Random Generated Vector is:\n",b)

Random Generated Co-efficient matrix is:
 [[-1.623   0.8066 -0.5093]
 [-0.1561  0.6837 -0.2813]
 [ 0.0026  0.418  -0.5089]]
Random Generated Vector is:
 [[0.08866367]
 [0.38132434]
 [0.08682732]]


In [13]:
def GaussJacobiSolution(A,b):
    ITERATION_LIMIT = 1000

    # prints the system
    print("System of equations to be solved using Gauss Jacobi:")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print(" + ".join(row), "=", b[i])
    print()

    x = np.zeros_like(b)
    for it_count in range(ITERATION_LIMIT):
        if it_count != 0:
            print("Iteration {0}: {1}".format(it_count, x))
        x_new = np.zeros_like(x)

        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x[:i])
            s2 = np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
            if x_new[i] == x_new[i-1]:
                break

        if np.allclose(x, x_new, atol=0.01, rtol=0.):
            break

        x = x_new

    print("Solution:")
    print(x)
    error = np.dot(A, x) - b
    print("Error:")
    print(error)

In [14]:
def GaussSeidelSolution(A,b):
    ITERATION_LIMIT = 1000

    # prints the system
    print("System of equations to be solved using Gauss ssiedel:")
    for i in range(A.shape[0]):
        row = ["{}x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), b[i]))

    x = np.zeros_like(b)
    for it_count in range(1, ITERATION_LIMIT):
        x_new = np.zeros_like(x)
        print("Iteration {0}: {1}".format(it_count, x))
        for i in range(A.shape[0]):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if np.allclose(x, x_new, rtol=0.01):
            break
        x = x_new

    print("Solution: {0}".format(x))
    error = np.dot(A, x) - b
    print("Error: {0}".format(error))

In [15]:
GaussJacobiSolution(A,b)

System of equations to be solved using Gauss Jacobi:
-1.623x1 + 0.8066x2 + -0.5093x3 = [0.08866367]
-0.1561x1 + 0.6837x2 + -0.2813x3 = [0.38132434]
0.0026x1 + 0.418x2 + -0.5089x3 = [0.08682732]

Iteration 1: [[-0.0546295 ]
 [ 0.55773635]
 [-0.17061764]]
Iteration 2: [[0.2760949 ]
 [0.475065  ]
 [0.28721643]]
Iteration 3: [[0.09133976]
 [0.73894506]
 [0.22100157]]
Iteration 4: [[0.24326144]
 [0.66951912]
 [0.43680331]]
Iteration 5: [[0.14103914]
 [0.79299433]
 [0.38055444]]
Iteration 6: [[0.22005495]
 [0.74651238]
 [0.48145219]]
Iteration 7: [[0.16529243]
 [0.80606614]
 [0.44367657]]
Iteration 8: [[0.20674356]
 [0.77802064]
 [0.49231301]]
Iteration 9: [[0.17754329]
 [0.80749549]
 [0.46948879]]
Iteration 10: [[0.199354  ]
 [0.79143783]
 [0.49354964]]
Iteration 11: [[0.18382332]
 [0.80631712]
 [0.48047164]]
Iteration 12: [[0.19532194]
 [0.79739043]
 [0.49261384]]
Solution:
[[0.19532194]
 [0.79739043]
 [0.49261384]]
Error:
[[-0.01338429]
 [-0.00521053]
 [-0.00370146]]


In [16]:
GaussSeidelSolution(A,b)

System of equations to be solved using Gauss Jacobi:
[-1.623x1 + 0.8066x2 + -0.5093x3] = [[0.08866367]]
[-0.1561x1 + 0.6837x2 + -0.2813x3] = [[0.38132434]]
[0.0026x1 + 0.418x2 + -0.5089x3] = [[0.08682732]]
Iteration 1: [[0.]
 [0.]
 [0.]]
Iteration 2: [[-0.0546295 ]
 [ 0.54526353]
 [ 0.27697152]]
Iteration 3: [[0.12944196]
 [0.70124663]
 [0.40603326]]
Iteration 4: [[0.1664628 ]
 [0.76279997]
 [0.45678105]]
Iteration 5: [[0.18112889]
 [0.78702804]
 [0.47675642]]
Iteration 6: [[0.18690148]
 [0.79656464]
 [0.48461908]]
Iteration 7: [[0.18917367]
 [0.80031841]
 [0.48771396]]
Solution: [[0.18917367]
 [0.80031841]
 [0.48771396]]
Error: [[ 0.00145157]
 [-0.00087059]
 [ 0.        ]]


In [17]:
#Generate Non Diagonally Dominant Random Matrix 
def generateNDD():
    A = getRandomMatrix()
    D = np.diag(np.abs(A)) # Find diagonal coefficients
    S = np.sum(np.abs(A), axis=1) - D # Find row sum without diagonal
    if all(D < S):
        return A
    else:
        return generateNDD()
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

In [18]:
AA = generateNDD()
if is_pos_def(AA):
    AA = generateNDD()
print("Non Diagonally Dominant Random Matrix is:\n",AA)

Non Diagonally Dominant Random Matrix is:
 [[ 1.3691 -2.0383  0.5169]
 [ 0.6485  0.2693 -0.303 ]
 [ 2.0148  1.2534 -0.1515]]


In [19]:
def NDDSolutionAttempt(AA,b):
    ITERATION_LIMIT = 1000

    # prints the system
    print("System of equations to be solved using Non Diagonally Dominant Random Matrix:")
    for i in range(AA.shape[0]):
        row = ["{}x{}".format(AA[i, j], j + 1) for j in range(AA.shape[1])]
        print(" + ".join(row), "=", b[i])
    print()

    x = np.zeros_like(b)
    for it_count in range(ITERATION_LIMIT):
        if it_count != 0:
            print("Iteration {0}: {1}".format(it_count, x))
        x_new = np.zeros_like(x)

        for i in range(AA.shape[0]):
            s1 = np.dot(AA[i, :i], x[:i])
            s2 = np.dot(AA[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / AA[i, i]
            if x_new[i] == x_new[i-1]:
                break

        if np.allclose(x, x_new, atol=0.01, rtol=0.):
            break

        x = x_new

    print("Solution:")
    print(x)
    error = np.dot(AA, x) - b
    print("Error:")
    print(error)

In [20]:
NDDSolutionAttempt(AA,b)

00222316e+269]
 [9.43596929e+269]
 [2.87786922e+270]]
Iteration 540: [[3.18284288e+269]
 [2.99665875e+270]
 [9.13948721e+270]]
Iteration 541: [[1.01080170e+270]
 [9.51673696e+270]
 [2.90250249e+271]]
Iteration 542: [[3.21008662e+270]
 [3.02230881e+271]
 [9.21771707e+271]]
Iteration 543: [[1.01945373e+271]
 [9.59819590e+271]
 [2.92734661e+272]]
Iteration 544: [[3.23756340e+271]
 [3.04817842e+272]
 [9.29661657e+272]]
Iteration 545: [[1.02817981e+272]
 [9.68035216e+272]
 [2.95240337e+273]]
Iteration 546: [[3.26527556e+272]
 [3.07426944e+273]
 [9.37619146e+273]]
Iteration 547: [[1.03698053e+273]
 [9.76321163e+273]
 [2.97767461e+274]]
Iteration 548: [[3.29322489e+273]
 [3.10058381e+274]
 [9.45644741e+274]]
Iteration 549: [[1.04585663e+274]
 [9.84678029e+274]
 [3.00316218e+275]]
Iteration 550: [[3.32141331e+274]
 [3.12712342e+275]
 [9.53739034e+275]]
Iteration 551: [[1.05480871e+275]
 [9.93106431e+275]
 [3.02886789e+276]]
Iteration 552: [[3.34984316e+275]
 [3.15389018e+276]
 [9.61902614e+276